[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
base.path = "../base"
cosync = "0.2.1"
froql = { version = "0.1.0", path = "../../fast_queries/froql" }
nanoserde.workspace = true