[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
base.path = "../base"
fastnoise-lite = "1.1.1"
froql.workspace = true
quicksilver.workspace = true
simple-easing = "1.0.1"
